version: "3.9"

services:
  ubuntu_vm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-virtual-machine
    volumes:
      - .:/projects
    working_dir: /projects
    stdin_open: true
    tty: true
    # ports:
    #   - "3000:3000"
    #   - "4200:4200"
    #   - "3001:3001"
    #   - "4000:4000"
    #   - "4001:4001"
    #   - "5001:5001"
    #   - "6000:6000"
    #   - "6001:6001"
    #   - "7000:7000"
    #   - "5000:5050"
    #   - "3501:3501"
    #   - "3502:3502"
    #   - "3500:3500"

