version: "3.9"

services:
  ubuntu_vm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-virtual-machine
    volumes:
      - .:/projects
    working_dir: /projects
    stdin_open: true
    tty: true

