# services:
#   app:
#     container_name: kaminari-staging
#     build:
#       context: .
#       args:
#         APP_ENV: staging
#     env_file: .env.staging
#     ports:
#       - "3501:3000"
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://staging.kaminari.com:3000"]
#       interval: 30s
#       timeout: 10s
#       retries: 3
#       start_period: 10s
#     environment:
#       - NEXT_LOG_LEVEL=verbose
#     volumes:
#       - .:/app
#       - /app/node_modules
#     networks:
#       - shared-db-net

# networks:
#   shared-db-net:
#     external: true

version: "3.8"

services:
  kaminari-staging:
    container_name: kaminari-staging
    build:
      context: .
      args:
        APP_ENV: staging
    env_file: .env.staging
    environment:
      - NEXT_LOG_LEVEL=verbose
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shared-db-net

networks:
  shared-db-net:
    external: true
