version: "3.8"

services:
  frontend:
    container_name: employee-management-frontend-dev
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        APP_ENV: development
    volumes:
      - proxy_employee-management-static-dev:/app/build
    networks:
      - shared-db-net

  backend:
    container_name: employee-management-backend-dev
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - ./server/.env.development
    networks:
      - shared-db-net

volumes:
  proxy_employee-management-static-dev:
    external: true

networks:
  shared-db-net:
    external: true
