version: "3.9"

services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - shared-db-net
  mongo_db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB port
    volumes:
      - mongo_data:/data/db # Persistent volume for MongoDB data
    restart: always
    env_file: .env
    networks:
      - shared-db-net
  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      env_file: .env
      ports:
        - "5050:80"
      networks:
        - shared-db-net
      depends_on:
        - postgres_db

volumes:
  postgres_data:
  mongo_data:



networks:
  shared-db-net:
    external: true